site_name: "Maya's Kitchen API"
nav:
  - Home: index.md
  - Introduction: introduction.md
  - API Overview: api_overview.md
  - Dependencies: dependencies.md
  - Project Structure: project_structure.md
  - Usage:
      - API Endpoints: api_endpoints.md
      - Testing: testing.md
  - Contributing: contributing.md
repo_url: "https://github.com/MayaCamilleri16/mayakitchen"
plugins:
  - search
theme:
  name: readthedocs  
docs_dir: "docs" 
